export const FEATURE_PERMISSION = {
  MENU: 'MENU',
  PROGRAM: 'PROGRAM',
  CHANNEL_CODE: 'CHANNEL_CODE',
  REGION: 'REGION',
  DISTRICT: 'DISTRICT',
  BRANCH: 'BRANCH',
}

export const APPLICATION_LIST = {
  TELESALE: 'TELESALE',
  SALE_ORDERING: 'SALE_ORDERING',
}
